### ISSUE TITLE
Why two decorators?

### ISSUE THREAD

**Issue by nateroling** [Futhark/ngx-observable-input#19]
I'm just curious, would it be possible to do this with a single decorator?

Currently:
`@ObservableInput() @Input("url") public url$: Observable<string>;`

Why not:
`@ObservableInput("url") public url$: Observable<string>;`

I've taken a brief look at the @Input decorator and I have no idea what's going on there, so maybe this would be impossible for some reason, but... it would really clean things up a bit...

**Comment by Futhark** [comment]
Hi @nateroling! 
Unfortunately, it cannot be done this way since @Input is kind of "reserved word" for Angular compiler. It has a special meaning and is has its own transpilation rules. If there would be a mechanism to extend the compiler then it would be achievable.

**Comment by nateroling** [comment]
Ah, interesting. That makes sense, thanks for the answer! I've been poking around a few libraries for this and yours is definitely one of the nicest!
