### ISSUE TITLE
[question] why not return BehaviorSubject

### ISSUE THREAD

**Issue by CosticaPuntaru** [Futhark/ngx-observable-input#3]
is there a reason behind returning BehaviorSubject.asObservable  in stead of returning BehaviorSubject directly ? 

if its returned it will open up the `.getValue(): T` improving usage for https://github.com/Futhark/ngx-observable-input/issues/1 as well

**Comment by Futhark** [comment]
I think that exposing Subject could enable harmful interactions. While a Subject is an Observable it also exposes methods like `complete` or `next` which could break the decorator. For example, if you would call `complete` on such subject then all the updates to the observed input attribute would stop.

If I may ask, why do you need async and sync access to that input field at the same time? I would say that in most cases you should decide to go one way or another in your component's architecture.

**Comment by CosticaPuntaru** [comment]
`If I may ask, why do you need async and sync access to that input field at the same time? I would say that in most cases you should decide to go one way or another in your component's architecture.`
i agree
