### ISSUE TITLE
How to unit test using observable inputs

### ISSUE THREAD

**Issue by GerkinDev** [Futhark/ngx-observable-input#4]
Hi,

I'm trying to write unit tests on a component using your observable inputs. While I can do what I want by manually triggering ngOnChanges, I don't know how to trigger changes on observable inputs, since those are not Subjects (as explained in #3).

Have you any idea on how I can dispatch new values from my tests ?

:beers: cheers ! (in a COVID safe way ofc ^^)

**Comment by GerkinDev** [comment]
Well ! I've found my way ! By looking at the source code, I saw you just override the `set` to emit a new value through the observable retrievable with `get`. So I just assigned to my property.

```ts
( myDirective.myObservableInput$ as any ) = 42
```

And magic ! It emits the value.

**Comment by Futhark** [comment]
@GerkinDev I'm happy that you've found a way to test it! And sorry for no previous response - I'm still on vacation without access to the computer.
